/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/App.tsx",
    "./src/main.tsx",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/contexts/**/*.{js,ts,jsx,tsx}",
    "./src/services/**/*.{js,ts,jsx,tsx}",
    "./src/types/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-red-500',
    'bg-white',
    'p-8',
    'rounded-lg',
    'shadow-lg',
    'text-xl',
    'font-bold',
    'text-sm',
    'text-gray-500',
    'mt-2',
    'min-h-screen',
    'flex',
    'items-center',
    'justify-center',
    'text-center',
    'animate-spin',
    'rounded-full',
    'h-12',
    'w-12',
    'border-b-2',
    'border-blue-600',
    'mx-auto',
    'mb-4',
    'text-gray-600',
    'bg-gray-50',
    'h-full',
    'flex-1',
    'overflow-auto'
  ],
  theme: {
    extend: {
      fontFamily: {
        'sans': ['Pretendard', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'Roboto', 'Helvetica Neue', 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'sans-serif'],
      },
    },
  },
  plugins: [],
}